# Generated by Django 4.1.3 on 2022-11-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_lyrics_song_song_artiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='Song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='Artiste',
        ),
    ]
